name: CI

on: [push]

jobs:
  build:
    name: Build with tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        env:
          COTEJI_JIRA_API_TOKEN: ${{ secrets.COTEJI_JIRA_API_TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew test
      - name: Code coverage check
        run: |
          ./gradlew jacocoTestCoverageVerification
      - name: Send code coverage
        uses: codecov/codecov-action@v2
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
          verbose: true
          version: v0.1.3
