name: CI

on: [push]

jobs:
  build:
    name: Build with tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        env:
          COTEJI_JIRA_API_TOKEN: ${{ secrets.COTEJI_JIRA_API_TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew test
